{% set version = "2.7.6" %}
{% set name = "oskar" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/OxfordSKA/OSKAR/archive/refs/tags/{{version}}.tar.gz
  sha256: c53e40ad3aae4747c480b220deb71bd457b172d1029e7f1f323b568a74d0e075

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sysroot_linux-64=2.17
    - cmake
    - make
  host:
    - python
    - pip
    - setuptools
    - casacore
  run:
    - python
    - numpy
    - casacore

test:
  imports:
    - oskar

about:
  home: https://github.com/OxfordSKA/OSKAR
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'SKA Radio Telescope Simulator'
  description: |
    The OSKAR package consists of a number of applications for the simulation of astronomical radio interferometers.
    OSKAR has been designed primarily to produce simulated data from telescopes that use aperture arrays, as envisaged for the SKA.
  doc_url: https://ska-telescope.gitlab.io/sim/oskar/
  dev_url: https://github.com/OxfordSKA/OSKAR

extra:
  recipe-maintainers:
    - Christoph Vögele
