name: Build Binary Packages Linux

on: [ push ]

jobs:
  build_binaries:
    runs-on: ubuntu-20.04
    container: ubuntu
    steps:
      - name: Install build dependencies
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y wget build-essential cmake gfortran g++ libncurses5-dev \
          libreadline-dev flex bison libblas-dev liblapacke-dev libcfitsio-dev \
          wcslib-dev libfftw3-dev tree
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build Casacore And Oskar
        run: |
          chmod +x build.sh
          bash -e build.sh
      - name: Archive binaries
        uses: actions/upload-artifact@v2
        with:
          name: Binaries Linux
          path: ~/binary-package/binaries-Linux.tar.gz
  install_binaries:
    needs: build_binaries
    runs-on: ubuntu-20.04
    container: ubuntu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          name: Binaries Linux
      - name: Install essential components
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y git wget unzip python3 python3-pip
      - name: Install
        shell: bash
        run: |
          chmod +x install-package.sh
          bash -e install-package.sh ~/pipeline
      - name: Test
        shell: bash
        run: |

      - name: Save test result
        uses: actions/upload-artifact@v2
        with:
          name: Test Results ${{ runner.os }}
          path: |
            result.vis
            result.ms
  publish_binaries:
    needs: install_binaries
    runs-on: ubuntu-20.04
    container: ubuntu
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          name: Binaries Linux
      - name: debug
        run: |
          ls
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./binaries-Linux.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: test
