name: Build Conda Package

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-20.04
    container: ubuntu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install cuda
        run: |
          apt-get update && apt-get install -y gnupg2 software-properties-common wget
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
          mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
          wget https://developer.download.nvidia.com/compute/cuda/11.6.0/local_installers/cuda-repo-ubuntu2004-11-6-local_11.6.0-510.39.01-1_amd64.deb
          dpkg -i cuda-repo-ubuntu2004-11-6-local_11.6.0-510.39.01-1_amd64.deb
          apt-key add /var/cuda-repo-ubuntu2004-11-6-local/7fa2af80.pub
          apt-get update
          DEBIAN_FRONTENT=noninteractive apt-get -y install cuda
      - name: Install dependencies
        run: |
          conda install conda-build
      - name: Build conda
        run: |
          cd conda/oskar
          conda build . -c conda-forge
      - name: Upload built package as artifact
        uses: actions/upload-artifact@v2
        with:
          name: conda package
          path: /usr/local/conda-bld/linux-64/oskar-*.tar.bz2
      - name: Install Anaconda for Upload
        run: |
          conda install anaconda
      - name: Publish to Conda
        run: |
          anaconda -t ${{ secrets.ANACONDA_SECRET }} upload /usr/local/conda-bld/linux-64/oskar-*.tar.bz2 --force
