name: Build Conda Package

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-20.04
    container: conda/miniconda3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          conda install conda-build
      - name: Build conda
        run: |
          cd conda/oskar
          conda build . -c conda-forge
      - name: Upload built package as artifact
        uses: actions/upload-artifact@v2
        with:
          name: conda package
          path: /usr/local/conda-bld/linux-64/oskar-*.tar.bz2
      - name: Publish to Conda
        run: |
          anaconda -t ${{ secret.ANACONDA_TOKEN }} upload /usr/local/conda-bld/linux-64/oskar-*.tar.bz2