name: Build Binary Packages Linux, MacOS

on: [ push ]

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    container: ubuntu
    steps:
      - name: Install build tools
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y git build-essential cmake python3
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Package
        run: |
          chmod +x package.sh
          bash -e package.sh
      - name: Archive binaries
        uses: actions/upload-artifact@v2
        with:
          name: OSKAR Binaries ${{ runner.os }}
          path: |
            oskar-binaries-${{ runner.os }}-x86_64.tar.gz
  download_and_test:
    needs: build_and_upload
    runs-on: ubuntu-latest
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          name: OSKAR Binaries ${{ runner.os }}
      - name: Install and test
        shell: bash
        run: |
          tar -xvzf oskar-binaries-${{ runner.os }}-x86_64.tar.gz
          cd package-${{ runner.os }}
          chmod +x test.sh
          chmod +x install.sh
          bash -e install.sh
          bash -e test.sh
      - name: Save test result
        uses: actions/upload-artifact@v2
        with:
          name: Test Results ${{ runner.os }}
          path: |
            ${{ github.workspace }}/result.vis
