name: Build Linux Binary Package

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: package in tar.gz linux
        run: |
          chmod +x package.sh
          ./package.sh
      - name: Archive binaries
        uses: actions/upload-artifact@v2
        with:
          name: dist-without-markdown
          path: |
            oskar-binaries-linux-x86_64.tar.gz
