name: Build Conda Package

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-20.04
    container: conda/miniconda3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install cuda
        run: |
          apt-get update && apt-get install -y gnupg2 software-properties-common
          apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/debian11/x86_64/7fa2af80.pub
          add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/debian11/x86_64/ /"
          add-apt-repository contrib
          apt-get update
          apt-get -y install cuda
      - name: Install dependencies
        run: |
          conda install conda-build
      - name: Build conda
        run: |
          cd conda/oskar
          conda build . -c conda-forge
      - name: Upload built package as artifact
        uses: actions/upload-artifact@v2
        with:
          name: conda package
          path: /usr/local/conda-bld/linux-64/oskar-*.tar.bz2
      - name: Install Anaconda for Upload
        run: |
          conda install anaconda
      - name: Publish to Conda
        run: |
          anaconda -t ${{ secrets.ANACONDA_SECRET }} upload /usr/local/conda-bld/linux-64/oskar-*.tar.bz2 --force
