name: Build Conda Package

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Cuda
        uses: Jimver/cuda-toolkit@v0.2.5
        with:
          cuda: '11.5.1'
      - name: install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
      - name: Install dependencies
        run: |
          sudo apt-get install gcc-multilib g++-multilib
          conda install conda-build
      - name: Build conda
        run: |
          cd conda/oskar
          conda build . -c conda-forge
      - name: Upload built package as artifact
        uses: actions/upload-artifact@v2
        with:
          name: conda package
          path: /usr/local/conda-bld/linux-64/oskar-*.tar.bz2
      - name: Install Anaconda for Upload
        shell: bash -l {0}
        run: |
          conda activate base
          conda install anaconda
      - name: Publish to Conda
        shell: bash -l {0}
        run: |
          conda activate base
          anaconda -t ${{ secrets.ANACONDA_SECRET }} upload /usr/local/conda-bld/linux-64/oskar-*.tar.bz2 --force
