name: Build Conda Package

on: [ push ]

jobs:
  check_tags:
    runs-on: ubuntu-latest
    steps:
    - name: Check tags in other repository
      uses: cvoegele/action-check-tags-in-another-repo@v1.0.0
      id: check
      with:
        other-repo-name: OSKAR
        other-repo-owner: OxfordSKA
    outputs:
      versions_to_build: ${{ steps.check.outputs.tags }}

  build_and_upload:
    needs: check_tags
    strategy:
      fail-fast: false # don't stop when one build fails
      matrix:
        os: [ macos-10.15, ubuntu-20.04 ]
        version: ${{ fromJson(needs.check_tags.outputs.versions_to_build) }}

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Cuda
        if: matrix.os == 'ubuntu-20.04'
        uses: Jimver/cuda-toolkit@v0.2.5
        with:
          cuda: '11.5.1'
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
      - name: Install dependencies Linux
        if: matrix.os == 'ubuntu-20.04'
        run: |
          sudo apt-get install gcc-multilib g++-multilib
      - name: Install dependencies MacOS
        if: matrix.os == 'macOS-10.15'
        run: |
          brew install libomp
      - name: Install Conda Build
        run: |
          conda install conda-build
          conda install anaconda
      - name: Build conda
        run: |
          cd conda/oskar
          var="{% set version = "${{ matrix.version }}" %}"
          sed -i "1s/.*/$var/" meta.yaml
          conda config --append channels conda-forge
          conda build .
      - name: Publish to Conda MacOS
        if: matrix.os == 'macOS-10.15'
        shell: bash -l {0}
        run: |
          conda activate base
          anaconda -t ${{ secrets.ANACONDA_SECRET }} upload /usr/local/miniconda/conda-bld/osx-64/oskar-*.tar.bz2 --force
      - name: Publish to Conda Linux
        if: matrix.os == 'ubuntu-20.04'
        shell: bash -l {0}
        run: |
          conda activate base
          anaconda -t ${{ secrets.ANACONDA_SECRET }} upload /usr/share/miniconda/conda-bld/linux-64/oskar-*.tar.bz2 --force

  install_and_test:
    needs: build_and_upload
    strategy:
      matrix:
        os: [ macos-10.15, ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
      - name: Install Package
        shell: bash -l {0}
        run: |
          conda activate base
          conda config --append channels conda-forge
          conda install -c i4ds oskar
