name: Build Mac Binary Package

on: [push]

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Package
        run: |
          chmod +x package.sh
          ./package.sh
      - name: Archive binaries
        uses: actions/upload-artifact@v2
        with:
          name: dist-without-markdown
          path: |
            oskar-binaries-${{ runner.os }}-x86_64.tar.gz
