name: Build Conda Package

on: [ push ]

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-10.15,  ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Cuda
        if: matrix.os == 'ubuntu-20.04'
        uses: Jimver/cuda-toolkit@v0.2.5
        with:
          cuda: '11.5.1'
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
      - name: Install dependencies Linux
        if: matrix.os == 'ubuntu-20.04'
        run: |
          sudo apt-get install gcc-multilib g++-multilib
      - name: Install dependencies MacOS
        if: matrix.os == 'macOS-10.15'
        run: |
          brew install libomp
          
          git clone https://github.com/google/googletest
          cd googletest
          mkdir build
          cd build
          cmake ..
          make
          sudo make install
          cd ../..
          rm -rf googletest
      - name: Install Conda Build
        run: |
          conda install conda-build
          conda install anaconda
#          conda config --set anaconda_upload yes
      - name: Build conda
        run: |
          cd conda/oskar
          conda build . -c conda-forge
      - name: Upload built package as artifact
        uses: actions/upload-artifact@v2
        with:
          name: conda package
          path: /usr/share/miniconda/conda-bld/*-64/oskar-*.tar.bz2
      - name: Publish to Conda MacOS
        if: matrix.os == 'macOS-10.15'
        shell: bash -l {0}
        run: |
          conda activate base
          anaconda -t ${{ secrets.ANACONDA_SECRET }} upload /usr/local/miniconda/conda-bld/osx-64/oskar-*.tar.bz2 --force
      - name: Publish to Conda Linux
        if: matrix.os == 'ubuntu-20.04'
        shell: bash -l {0}
        run: |
          conda activate base
          anaconda -t ${{ secrets.ANACONDA_SECRET }} upload /usr/share/miniconda/conda-bld/linux-64/oskar-*.tar.bz2 --force
